<?php
/**
 * 玩家互动表情
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/4/8
 * Time: 13:39
 * @author Zhanghui
 */

class playeremoticonredistask extends basicredistask {

    public function __construct()
    {
        parent::__construct();

        $this->init_redis_fields();

        $this->set_redis_name('redis_user');
        $this->set_redis_keys_info('player_emotcion', 'player_id');
        $this->set_redis_database_model(1, true);
    }

    public function on_redis_task(basicredis $redis, basicmodel $model = null, $param, $default)
    {
        return parent::on_redis_task($redis, $model, $param, $default); // TODO: Change the autogenerated stub
    }

    protected function build_redis_keys(basicredis $redis, basicmodel $model)
    {
        if (is_null($model)) {
            return '';
        }

        $player_id = $model->get($this->m_redis_fields, 0);
        $index = $player_id % 1000;
        $keys = floor($index / 10);
        $prop_id = $model->get('prop_id', 0);

        return $this->m_redis_keys.':'.$keys.':'.$player_id.':'.$prop_id;
    }

    protected function init_redis_fields()
    {
        $this->set_fields_default('player_id', 'player_id', 0);
        $this->set_fields_default('prop_id', 'prop_id', 0);
        $this->set_fields_default('prop_price', 'prop_price', 0);
        $this->set_fields_default('prop_limit_times', 'prop_limit_times', -1);
        $this->set_fields_default('prop_available_times', 'prop_available_times', -1);
        $this->set_fields_default('prop_modify_time', 'prop_modify_time', time());
    }

    public function get_redis_key(basicmodel $model = null, $param, $default)
    {
        $player_id = $model->get($this->m_redis_fields, 0);
        $index = $player_id % 1000;
        $keys = floor($index / 10);
        $prop_id = $model->get('prop_id', 0);

        if (!$prop_id) {
            $prop_id = '*';
        }

        return $this->m_redis_keys.':'.$keys.':'.$player_id.':'.$prop_id;
    }
}