<?php
/**
 * 消息信息
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/22
 * Time: 17:31
 * @author Zhanghui
 */

class messagedatatask extends basicdatatask {

    public function __construct()
    {
        parent::__construct();

        basicfields::message_fields($this);

        $this->set_data_table_info('dc_message', 'message_id');
    }

    public function on_data_task(basicmysql $db, basicmodel $model = null, $param, $default)
    {
        return parent::on_data_task($db, $model, $param, $default); // TODO: Change the autogenerated stub
    }

}