<?php
/**
 * 玩家道具使用记录
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/3/20
 * Time: 18:02
 * @author Zhanghui
 */

class playerproplogdatatask extends basicdatatask {

    public function __construct()
    {
        parent::__construct();

        basicfields::playerproplog_fields($this);
        $this->set_data_table_info('dc_player_prop_log', 'log_id');
    }

    public function on_data_task(basicmysql $db, basicmodel $model = null, $param, $default)
    {
        return parent::on_data_task($db, $model, $param, $default); // TODO: Change the autogenerated stub
    }
}